### ISSUE TITLE
would like to become a contributor

### ISSUE THREAD

**Issue by edwinchenloo** [foxadb/yahoo-finance#1]
Thanks for writing the library.  I noticed some methods were missing 'const' modifiers.  I added them and made a few other optimizations dealing with passing by const references.  I could push to a branch and create a pull request but would need some permissions to do so.

**Comment by foxadb** [comment]
Hi @edwinchenloo!
I'm glad to hear that this library is helpful. Feel free to create a pull request 👍

**Comment by janulm** [comment]
Hey, when compiling the example I get the following error message: 

curl_utils.cpp:120:47: error: character '/' cannot be specified by a universal character name
    std::replace(crumb.begin(), crumb.end(), '\u002F', '/');
                                                                            ^~~~~~
1 error generated.
I am trying to run it on MacOS 11.2. I would be incredibly thankful for any help. Maybe you can contact me here and help get it running: jannek1ulm@gmail.com
Best regards, Jannek

**Comment by foxadb** [comment]
Hi @janulm, please continue the discussion on this issue https://github.com/foxadb/yahoo-finance/issues/9
