### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by janulm** [foxadb/yahoo-finance#9]
Hey, when compiling the example I get the following error message:

curl_utils.cpp:120:47: error: character '/' cannot be specified by a universal character name
std::replace(crumb.begin(), crumb.end(), '\u002F', '/');
^~~~~~
1 error generated.
I am trying to run it on MacOS 11.2. I would be incredibly thankful for any help.
Best regards, Jannek

**Comment by foxadb** [comment]
Hi @janulm, thanks for reporting this issue.
I have looked at the code a bit further and it seems that I could completely remove this faulty code.
I have submitted a PR (https://github.com/foxadb/yahoo-finance/pull/10), could you checkout the branch and test if the code compile on your environment?
